use `pred U` instead of `set U` in `patch`
- presentation becomes a big shorted except for the proof
  of `family_cvg_finite_covers`
- also lint in the process
- NB: remove algC and algnum from forms.v because they were causing
  an error in my setting:
```
File "./theories/derive.v", line 6, characters 0-39:
Error: Universe inconsistency. Cannot enforce
mathcomp.field.algebraics_fundamentals.12862 <= Coq.ssr.ssrfun.92 because
Coq.ssr.ssrfun.92 < mathcomp.field.algebraics_fundamentals.12862.
```